name-template: 'v$RESOLVED_VERSION - <Release Date>'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '💀 BREAKING CHANGES'
    labels:
      - 'breaking change'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    labels: 
      - 'chore'
      - 'CI/CD'
      - 'refactor'
      - 'test'
      - 'documentation'
      - 'performance'
      - 'revert'
change-template: '- $TITLE @$AUTHOR (#$NUMBER): $BODY'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'breaking change'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'CI/CD'
      - 'documentation'
      - 'test'
      - 'performance'
      - 'refactor'
      - 'chore'
      - 'revert'
  default: patch
template: |
  ## Changes

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
