name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '💀 BREAKING CHANGES'
    labels:
      - 'breaking change'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    labels: 
      - 'chore'
      - 'ci'
      - 'refactor'
      - 'test'
      - 'documentation'
      - 'performance'
      - 'revert'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'breaking change'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'CI/CD'
      - 'documentation'
      - 'test'
      - 'performance'
      - 'refactor'
      - 'chore'
      - 'revert'
  default: patch
template: |
  ## Changes

  $CHANGES
